services:
  db:
    image: postgres:16
    container_name: tender_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tender_dev
    ports:
      - "5432:5432"
    volumes:
      - tender_pgdata:/var/lib/postgresql/data

volumes:
  tender_pgdata:
